export const CLIENT_CLOCK_ON_SECOND_CHANGE = 'CLIENT_CLOCK_ON_SECOND_CHANGE';
export const CLIENT_CLOCK_ON_MINUTE_CHANGE = 'CLIENT_CLOCK_ON_MINUTE_CHANGE';
export const CLIENT_CLOCK_ON_HOUR_CHANGE = 'CLIENT_CLOCK_ON_HOUR_CHANGE';
export const CLIENT_CLOCK_ON_DAY_CHANGE = 'CLIENT_CLOCK_ON_DAY_CHANGE';
export const CLIENT_CLOCK_STOP = 'CLIENT_CLOCK_STOP';
